# Generated by Django 2.2 on 2020-10-22 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fname', models.CharField(default=' ', max_length=50, null=True)),
                ('client_lname', models.CharField(default=' ', max_length=50, null=True)),
                ('client_cell_phone', models.CharField(default=' ', max_length=50, null=True)),
                ('client_email', models.EmailField(default=' ', max_length=100)),
                ('client_address_line_1', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('client_address_line_2', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('client_address_city', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('client_address_state', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('client_address_zip', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('acct_number', models.CharField(blank=True, default='00000', max_length=50, null=True)),
                ('notes', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
