# Generated by Django 2.2 on 2020-10-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20201022_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.Client'),
        ),
    ]
