# Generated by Django 2.2 on 2020-10-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20201022_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='vehicle_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.Client'),
        ),
    ]
