# Generated by Django 2.2 on 2020-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20201114_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
