# Generated by Django 2.2 on 2020-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20201115_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
