# Generated by Django 2.2 on 2020-11-15 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20201115_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
    ]
