# Generated by Django 2.2 on 2020-11-15 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20201115_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
